server:
  port: 8888

spring:
  application:
    name: eureka

eureka:
  instance:
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${EUREKA_HOSTNAME:localhost}
    preferIpAddress: true
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka/}

